export interface Registro2{
   administrador:    '',
   canchaClases:     '',
   detalleHorario:   '', 
   direccion:        '', 
   email:            '', 
   giro:             '', 
   horaCancha:       '', 
   horaCanchaAM:     '', 
   horaCanchaPM:     '', 
   horarioClase:     '', 
   nombre:           '', 
   nombreNegocio:    '', 
   nombreRazon:      '', 
   numClases:        '', 
   numeroCanchas:    '', 
   participantes:    '', 
   rangoHorario1:    '', 
   rangoHorario2:    '', 
   rangoHorario3:    '', 
   rut:              '', 
   telefono:         '', 
   tieneClase:       '', 
   tieneHorario:     '', 
   valorClase:       '' 
}